version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_equipos
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: martin123
      POSTGRES_DB: equiposdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_equipos
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      FLASK_ENV: development

volumes:
  pgdata:
